### ISSUE TITLE
Adding Dimming Support

### ISSUE THREAD

**Issue by UniKyrn** [mmotley999/addons#1]
What would you need incentive/hardware/donation wise to add support for send/recv of the different forms of dimming?

I've got file cabinets full of devices going almost back to the original BSR stuff and since I'm retired I have the time to help out.  If you need hardware, you've got it.  Need a tester, I'm available.

**Comment by UniKyrn** [comment]
There doesn't seem to be a wiki, so I'll put this here, maybe to be added to the documentation.

Note: the existing on/off support is enough to support X10 motion sensors, here is an example:

```
binary_sensor:

  - platform: mqtt
    name: "Kitchen Motion Sensor (x10)"
    state_topic: "x10/stat/c9"
    payload_on: "ON"
    payload_off: "OFF"
    unique_id: "X10-C09"
    device_class: motion
    device:
      manufacturer: "X-10"
      model: "Unknown"
      identifiers: "X10-C09"
      name: "Hawkeye II"

  - platform: mqtt
    name: "Kitchen Dark Sensor (x10)"
    state_topic: "x10/stat/c10"
    payload_on: "ON"
    payload_off: "OFF"
    unique_id: "X10-C10"
    device_class: light
    device:
      manufacturer: "X-10"
      model: "Unknown"
      identifiers: "X10-C10"
      name: "Hawkeye II"
```

Defining them as the motion device class allows them to be used by the native Alarm or Alarmo Integrations
